# Generated by Django 4.1.2 on 2022-10-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
